# Generated by Django 6.0.4 on 2026-04-15 03:33

import bot_test2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=bot_test2.models.uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('gender_probability', models.FloatField(blank=True, null=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('country_id', models.CharField(blank=True, max_length=10, null=True)),
                ('country_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
